### ISSUE TITLE
Version conflict: scalac-scoverage-reporter and coursier-core

### ISSUE THREAD

**Issue by d10xa** [d10xa/jadd#603]
CI run fails
https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973

```
Run sbt -v coverage test
  sbt -v coverage test
  shell: /usr/bin/bash -e {0}
  env:
    CI: true
    JAVA_HOME: /home/runner/.jabba/jdk/adopt@1.11.0-11
[sbt_options] declare -a sbt_options=()
[process_args] java_version = '11'
downloading sbt launcher 1.7.1
[copyRt] java9_rt = '/home/runner/.sbt/1.0/java9-rt-ext-adoptopenjdk_11_0_11/rt.jar'
copying runtime jar...
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms10[2](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:2)4m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dsbt.script=/home/runner/bin/sbt
-Dscala.ext.dirs=/home/runner/.sbt/1.0/java9-rt-ext-adoptopenjdk_11_0_11
-jar
/home/runner/.cache/sbt/boot/sbt-launch/1.7.1/sbt-launch-1.7.1.jar
coverage
test

[info] welcome to sbt 1.8.0 (AdoptOpenJDK Java 11.0.11)
[info] loading settings for project jadd-build from plugins.sbt ...
[info] loading project definition from /home/runner/work/jadd/jadd/project
[info] loading settings for project root from build.sbt ...
[info] set current project to jadd (in build file:/home/runner/work/jadd/jadd/)
[info] Defining ThisBuild / coverageEnabled
[info] The new value will be used by Compile / compile / scalacOptions, libraryDependencies
[info] Reapplying settings...
[info] set current project to jadd (in build file:/home/runner/work/jadd/jadd/)
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-xml_2.1[3](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:3):2.1.0 (early-semver) is selected over 1.3.0
[error] 	    +- org.scoverage:scalac-scoverage-reporter_2.13:2.0.7 (depends on 2.1.0)
[error] 	    +- io.get-coursier:coursier-core_2.13:2.0.16          (depends on 1.3.0)
[error] 
[error] 
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:1[4](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:4)6)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:26[5](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:5))
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:[6](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:6)4)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-xml_2.13:2.1.0 (early-semver) is selected over 1.3.0
[error] 	    +- org.scoverage:scalac-scoverage-reporter_2.13:2.0.[7](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:8) (depends on 2.1.0)
[error] 	    +- io.get-coursier:coursier-core_2.13:2.0.16          (depends on 1.3.0)
[error] 
[error] 
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] Total time: 2 s, completed Dec 21, 2022, [8](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:9):[15](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:16):[52](https://github.com/d10xa/jadd/actions/runs/3752515459/jobs/6374762973#step:5:53) PM

Error: Process completed with exit code 1.
```

**Comment by d10xa** [comment]
Temporary disable code coverage.
Uncomment lines to rollback:

 - .github/workflows/build.yml
```diff

    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and Test
+        # run: sbt -v coverage test
        run: sbt -v test
+ #      - name: Coverage report
+ #        run: sbt coverageReport
+ #      - name: Upload coverage to Codecov
+ #        uses: codecov/codecov-action@260aa3b4b2f265b8578bc0e721e33ebf8ff53313
+ #        with:
+ #          fail_ci_if_error: true
      - name: Cleanup
        run: |
          rm -rf "$HOME/.ivy2/local" || true
```

- .mergify.yml
```diff
    conditions:
      - author=scala-steward
      - check-success=build
+ #      - check-success=codecov/patch
    actions:
      merge:
        method: squash
```

- project/plugins.sbt
```diff
+ //addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.6")
```
